[package]
name = "yarte_derive"
version = "0.6.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Procedural macro package for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_derive"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[features]
mime = ["yarte_codegen/mime"]
client = ["yarte_hir/client", "yarte_codegen/client", "yarte_helpers/big_num"]
actix-web = ["yarte_hir/actix-web", "yarte_codegen/actix-web"]

[dependencies]
yarte_codegen = { version = "0.6", path = "../yarte_codegen" }
yarte_config = { version = "0.6", path = "../yarte_config" }
yarte_helpers = { version = "0.6", path = "../yarte_helpers" }
yarte_hir = { version = "0.6", path = "../yarte_hir" }
yarte_parser = { version = "0.6", path = "../yarte_parser" }

prettyprint = "0.7"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
syn = "1.0"
tempfile = "3.0"
toolchain_find = "0.1"
