[package]
name = "yarte_derive"
version = "0.7.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Procedural macro package for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_derive"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[features]
mime = ["yarte_codegen/mime"]
wasm-app = ["yarte_hir/wasm-app", "yarte_codegen/wasm-app", "yarte_helpers/big_num_32"]
actix-web = ["yarte_hir/actix-web", "yarte_codegen/actix-web"]

[dependencies]
yarte_codegen = { version = "0.7.0", path = "../yarte_codegen" }
yarte_helpers = { version = "0.7.0", path = "../yarte_helpers" }
yarte_hir = { version = "0.7.0", path = "../yarte_hir" }
yarte_parser = { version = "0.7.0", path = "../yarte_parser" }

prettyprint = "0.8"

proc-macro2-impersonated = "0.1"
quote-impersonated = "0.1"
syn-impersonated = "0.1"

tempfile = "3.0"
toolchain_find = "0.1"
