[package]
name = "yarte_derive"
version = "0.3.5"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Procedural macro package for yarte"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte_derive"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[features]
actix-web = []

[dependencies]
yarte_config = { version = "0.3", path = "../yarte_config" }
v_htmlescape = "0.4"
v_eval = "0.2"
memchr = "2.1"
mime_guess = "2.0"
nom = "4"
prettyprint = "0.7"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version="1.0", features = ["full", "visit", "extra-traits"]}
toolchain_find = "0.1"
tempfile = "3.0"
