language: rust
sudo: false
dist: trusty

cache:
  cargo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.45.0
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
      rustup component add clippy
    fi

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
      cargo clippy --all-targets --all-features
    fi
  - cargo test --all-features --all -- --nocapture
  - |
    cd yarte && cargo test -- --nocapture       \
    && cargo test --release --all-features -- --nocapture       \
    && cargo test --features bytes-buf          \
    && cargo test --features bytes-buf-tokio2   \
    && cargo test --features fixed              \
    && cargo test --features json               \
    && cargo test --features wasm               \
    && cd ..
