[workspace]
members = [
    "example",
    "yarte",
    "yarte_codegen",
    "yarte_config",
    "yarte_derive",
    "yarte_helpers",
    "yarte_hir",
    "yarte_parser",
    "yarte_template",
    "yarte_wasm_app"
]
