[workspace]
members = [
    "example",
    "yarte",
    "yarte_codegen",
    "yarte_derive",
    "yarte_helpers",
    "yarte_hir",
    "yarte_html",
    "yarte_parser",
    "yarte_wasm_app",
    "yarte_write",
]
