[package]
name = "yarte_parser"
version = "0.7.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Ast, lexer and parser for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_parser"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
yarte_helpers = { version = "0.7.0", path = "../yarte_helpers" }

annotate-snippets = { git = "https://github.com/rust-lang/annotate-snippets-rs", features = ["color"] }
derive_more = "0.99"

quote-impersonated = "0.1"
syn-impersonated = { version="0.1", features = ["full", "extra-traits"] }
proc-macro2-impersonated = { version = "0.1", features = ["span-locations"] }

unicode-xid = "0.2"
