[package]
name = "yarte_wasm_app"
version = "0.0.2"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Async core for yarte wasm applications"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte_wasm_app"
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dev-dependencies]
wasm-bindgen-futures = "0.4"
async-timer = "0.7"
wasm-bindgen-test = "0.3"
