[package]
name = "yarte_codegen"
version = "0.6.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Code generator for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_codegen"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
mime = ["mime_guess"]
client = ["indexmap", "heck", "yarte_hir/client", "yarte_dom/client", "yarte_helpers/big_num"]
actix-web = ["yarte_dom/actix-web", "yarte_hir/actix-web", "mime_guess"]

[dependencies]
yarte_dom = { version = "0.6", path = "../yarte_dom" }
yarte_helpers = { version = "0.6", path = "../yarte_helpers" }
yarte_hir = { version = "0.6", path = "../yarte_hir" }
yarte_html = { version = "0.6", path = "../yarte_html" }

proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }

markup5ever = "0.10"

heck = { version = "0.3", optional = true }
mime_guess = { version = "2.0", optional = true }
indexmap = { version = "1.3", optional = true }

[dev-dependencies]
yarte_parser = { version = "0.6", path = "../yarte_parser" }
