[package]
name = "yarte_codegen"
version = "0.4.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Code generator for yarte"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte_derive"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
actix-web = ["yarte_hir/actix-web"]

[dependencies]
yarte_hir = { version = "0.4", path = "../yarte_hir" }

mime_guess = "2.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = "1.0"
