[package]
name = "yarte_codegen"
version = "0.7.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Code generator for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_codegen"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
wasm-app = ["indexmap", "heck", "yarte_hir/wasm-app", "yarte_dom/wasm-app"]
html-min = ["yarte_dom", "yarte_html"]
wasm-server = ["yarte_dom", "yarte_html"]

[dependencies]
yarte_helpers = { version = "0.7.0", path = "../yarte_helpers" }
yarte_hir = { version = "0.7.0", path = "../yarte_hir" }

proc-macro2-impersonated = "0.1"
quote-impersonated = "0.1"
syn-impersonated = { version= "0.1", features = ["full", "extra-traits"] }

yarte_dom = { version = "0.7.0", path = "../yarte_dom", optional = true }
yarte_html = { version = "0.7.0", path = "../yarte_html", optional = true }
heck = { version = "0.3", optional = true }
mime_guess = { version = "2.0", optional = true }
indexmap = { version = "1.3", optional = true }

[dev-dependencies]
yarte_parser = { version = "0.7.0", path = "../yarte_parser" }
