[package]
name = "yarte_codegen"
version = "0.5.3"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Code generator for yarte"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte_codegen"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
actix-web = ["yarte_dom/actix-web", "yarte_hir/actix-web"]

[dependencies]
yarte_config = { version = "0.5", path = "../yarte_config" }
yarte_dom = { version = "0.5", path = "../yarte_dom" }
yarte_hir = { version = "0.5", path = "../yarte_hir" }

markup5ever = "0.10"
mime_guess = "2.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }
heck = "0.3"
[dev-dependencies]
yarte_parser = { version = "0.5", path = "../yarte_parser" }
