[package]
name = "yarte_helpers"
version = "0.10.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Helper collection for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_helpers"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[features]
big-num-32 = []
config = ["serde", "toml"]
default = ["markup", "config"]
display-fn = []
json = ["serde", "serde_json"]
ryu-ad = ["ryu"]
fixed = ["v_htmlescape", "itoa", "ryu-ad"]
markup = ["v_htmlescape", "itoa", "dtoa"]
bytes-buf = ["bytes", "v_htmlescape", "itoa", "ryu-ad"]

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
v_htmlescape = { version = "0.9", optional = true }
itoa = { version = "0.4", features = ["i128"], optional = true }
dtoa = { version = "0.4", optional = true }
ryu = { version = "1.0", optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }
toml = { version = "0.5", optional = true }
serde_json = { version = "1.0", optional = true }

bytes = { version = "0.5", optional = true }

[dev-dependencies]
serde_json = "1.0"

[package.metadata.docs.rs]
all-features = true
