[package]
name = "yarte_helpers"
version = "0.6.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Helper collection for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_helpers"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[features]
big_num = []

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
yarte_config = { version = "0.6", path = "../yarte_config" }
yarte_parser = { version = "0.6", path = "../yarte_parser" }
annotate-snippets = { version = "0.6", features = ["ansi_term"] }
v_htmlescape = "0.4"
