[package]
name = "yarte_helpers"
version = "0.7.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Helper collection for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_helpers"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[features]
big_num_32 = []
display_fn = []
io_fmt = ["display_fn"]

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
v_htmlescape = "0.4"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
serde_json = "1.0.51"
