[package]
name = "yarte_helpers"
version = "0.9.2"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Helper collection for yarte"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte_helpers"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[features]
default = ["markup", "config"]
markup = ["io-fmt", "v_htmlescape", "itoa", "dtoa"]
config = ["serde", "toml"]
big-num-32 = []
display-fn = []
io-fmt = ["display-fn", "serde_json"]

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
v_htmlescape = { version = "0.4", optional = true }
itoa = { version = "0.4", optional = true }
dtoa = { version = "0.4", optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }
toml = { version = "0.5", optional = true }
# dev-dependency io-fmt feature
serde_json = { version = "1.0.51", optional = true }

[package.metadata.docs.rs]
all-features = true
