[package]
name = "yarte"
version = "0.4.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Type-safe, compiled Handlebars"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte"
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
with-actix-web = ["actix-web", "futures", "yarte_derive/actix-web"]
full = ["with-actix-web"]

[dependencies]
yarte_derive = { version = "0.4", path = "../yarte_derive" }
yarte_helpers = { version = "0.4", path = "../yarte_helpers" }
yarte_config = { version = "0.4", path = "../yarte_config" }
actix-web = { version = "2.0.0-alpha", optional = true }
futures = { version = "0.3", optional = true }

[build-dependencies]
yarte_config = { version = "0.4", path = "../yarte_config" }

[dev-dependencies]
actix-rt = "1.0.0"
