[package]
name = "yarte"
version = "0.8.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Type-safe, compiled Handlebars"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte"
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
keywords = ["template", "handlebars", "html", "wasm"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
wasm = ["serde_json", "serde", "yarte_derive/wasm-server"]
json = ["serde_json", "serde", "yarte_helpers/io-fmt"]
html-min = ["yarte_derive/html-min"]

[dependencies]
yarte_derive = { version = "0.8.1", path = "../yarte_derive" }
yarte_helpers = { version = "0.8.1", path = "../yarte_helpers" }

serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

[build-dependencies]
yarte_helpers = { version = "0.8.1", path = "../yarte_helpers" }

[package.metadata.docs.rs]
all-features = true