[package]
name = "yarte"
version = "0.6.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Type-safe, compiled Handlebars"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte"
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
keywords = ["template", "handlebars", "html", "wasm"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
wasm = ["serde_json", "serde"]
mime = ["yarte_template/mime", "yarte_derive/mime"]
with-actix-web = ["actix-web", "futures", "yarte_derive/actix-web", "yarte_template/mime"]
client = ["yarte_helpers/big_num", "yarte_derive/client", "yarte_wasm_app", "wasm-bindgen", "web-sys", "serde_json", "serde"]

[dependencies]
yarte_derive = { version = "0.6", path = "../yarte_derive" }
yarte_helpers = { version = "0.6", path = "../yarte_helpers" }
yarte_template = { version = "0.6", path = "../yarte_template" }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

actix-web = { version = "2.0", optional = true }
futures = { version = "0.3", optional = true }

yarte_wasm_app = { version = "0.0", path = "../yarte_wasm_app", optional = true  }
wasm-bindgen = { version = "0.2", optional = true }
[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  "Node",
  "Document",
  "Window",
  "Element",
  "HtmlElement",
  "EventTarget",
  "Event",
  "HtmlCollection"
]


[build-dependencies]
yarte_helpers = { version = "0.6", path = "../yarte_helpers" }
