[package]
name = "yarte"
version = "0.5.3"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Type-safe, compiled Handlebars"
categories = ["template-engine", "web-programming", "gui"]
documentation = "https://docs.rs/yarte"
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
keywords = ["markup", "template", "handlebars", "html", "web", "wasm"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = []
wasm = ["serde_json", "serde", "serde_derive"]
with-actix-web = ["actix-web", "futures", "yarte_derive/actix-web"]
full = ["with-actix-web"]

[dependencies]
yarte_config = { version = "0.5", path = "../yarte_config" }
yarte_derive = { version = "0.5", path = "../yarte_derive" }
yarte_helpers = { version = "0.5", path = "../yarte_helpers" }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

actix-web = { version = "2.0", optional = true }
futures = { version = "0.3", optional = true }

[target.'cfg(target_arch="wasm32")'.dependencies]
yarte_wasm_app = { version = "0.0", path = "../yarte_wasm_app" }
serde_json = "1.0"
wasm-bindgen = "0.2"
[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
  "Node",
  "Document",
  "Window",
  "Element",
  "HtmlElement",
  "EventTarget",
  "Event",
  "HtmlCollection"
]


[build-dependencies]
yarte_config = { version = "0.5", path = "../yarte_config" }
