[package]
name = "worker-pool"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"
workspace = ".."

[dependencies]
utils = { path = "../utils" }
js-sys = "0.3.45"
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"

[dependencies.web-sys]
version = "0.3.45"
features = [
  "DedicatedWorkerGlobalScope",
  "ErrorEvent",
  "Event",
  "MessageEvent",
  "Worker",
]
