[package]
name = "client"
version = "0.1.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
edition = "2018"
workspace = ".."

[lib]
crate-type = ["cdylib"]

[dependencies]
worker-pool = { path = "../worker-pool" }
utils = { path = "../utils" }

yarte_wasm_app = "0.2.1"

raytracer = { git = "https://github.com/alexcrichton/raytracer", branch = "update-deps" }

rayon = "1.1.0"
rayon-core = "1.5.0"

futures = "0.3.5"

serde_json = "1.0.57"
serde = "1.0.116"

gloo-timers = { version = "0.2.1", features = ["futures"] }
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"
console_error_panic_hook = "0.1"
js-sys = "0.3.45"

[dependencies.web-sys]
version = "0.3.45"
features = [
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "Event",
    "HtmlButtonElement",
    "HtmlCanvasElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "ImageData",
    "Navigator",
    "Performance",
    "Window",
]
