[package]
name = "yarte_hir"
version = "0.4.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
description = "Intermediate representation for yarte"
categories = ["template-engine"]
documentation = "https://docs.rs/yarte_derive"
edition = "2018"
keywords = ["markup", "template", "handlebars", "html"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/botika/yarte"
workspace = ".."

[badges]
travis-ci = { repository = "botika/yarte", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
actix-web = []

[dependencies]
yarte_config = { version = "0.4", path = "../yarte_config" }
yarte_parser = { version = "0.4", path = "../yarte_parser" }
yarte_helpers = { version = "0.4", path = "../yarte_helpers" }
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = { version="1.0", features = ["full", "visit", "visit-mut", "extra-traits"]}
v_eval = "0.2"
v_htmlescape = "0.4"